### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by michael-e** [DeuxHuitHuit/sri#1]
The description says:

> A simple way to compute Subresource Indentity

which should be:

> A simple way to compute Subresource Integrity

**Comment by nitriques** [comment]
Oups ! Thanks @michael-e

**Comment by michael-e** [comment]
You're welcome. BTW, works like a charm!

(I don't actually need it, was just playing around in order to learn…)

**Comment by nitriques** [comment]
👍 

It can cause troubles when not used over TLS: some proxy will modified the resource and it will break, _per design_.

**Comment by michael-e** [comment]
Yeah, sure.

Still, I don't really get the value of SRI for local assets. I know that you get 5 extra points on https://observatory.mozilla.org if you do it. But why? Isn't SRI intended to be used with CDN assets in the first place? Or is it a "just to be even more secure, you never know" thingie?

**Comment by nitriques** [comment]
> Isn't SRI intended to be used with CDN assets in the first place? 

Yes indeed. That's primarily why I use it.

> Or is it a "just to be even more secure, you never know" thingie?

For "local" assets, yes it is. But again, you can't know for sure that your users talk you your server, [especially on mobile](https://bugs.chromium.org/p/chromium/issues/detail?id=642928)
